# Application Login details
username=upcagent1
password=UPC12345

BASE_URL=http://automationpractice.com

defaultBrowser=chrome
defaultExecutionEnvironment=Local
MACOSBUILD=Sierra

explicit_timeout=45
implicitlyWait=500
pageLoadTimeOut=600
polling_time=10

logInfoFilePath=ExecutionReports/Logs/appLog.txt
logErrorFilePath=ExecutionReports/Logs/errorLog.txt
logHtmlFilePath=ExecutionReports/Logs/appLogs.html
extentConfigPath=/src/main/resources/Config/extent-config.xml
extentReportPath=/ExecutionReports/HTMLReports/extentReport.html

#paths of files to get test data
DataSheetPath=DataSheet/DataSheet.xls
CvsDataSheetPath=DataSheet/
XmlDataSheetPath=DataSheet/DataSheet.xml
DataMode=xls
ReferenceNumberNote=DataSheet/ReferenceNote.txt

columnToLookTestCaseID=0
AutomationControlExcelPath=/src/test/resources/ExcelFiles/AutomationControlSheet.xlsx
testResultExcelPath=/ExecutionReports/ExcelReport/TestResult.xls
testDataSheet=TestData
testDataExcelPath=src/test/resources/testData/TestData.xlsx
testDataNykaaExcelPath=src/test/resources/testData/TestDataNykaa.xlsx

AutomationControlSheet=AppControl

HtmlReportFullPath=target/cucumber-html-report.html
screenshotPath=ExecutionReports/FailedScreenshots

GeckoDriverPath=src/main/resources/Driver/geckodriver.exe
IEDriverPath=src/main/resources/Driver/IEDriverServer.exe
ChromeDriverPath=src/main/resources/Driver/chromedriver.exe

# Number to times you want to retry a failed Test Case.
retryCount=0
#wait for given time in Secs before retry to execute Test Case.
retryDelayTime=1

HTMLReport=Y
ExcelReport=Y
Logs=N